/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from 'three'
import React, { useEffect, useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { GLTF } from 'three-stdlib'
import { useScrollbar } from '@14islands/r3f-scroll-rig'

type GLTFResult = GLTF & {
    nodes: {
        model: THREE.Mesh
    }
    materials: {
        model: THREE.MeshStandardMaterial
    }
}

interface LogoProps extends THREE.Group { }

export const Logo: React.FC<LogoProps> = (props) => {
    const { nodes, materials } = useGLTF('/shades-compressed.glb') as any as GLTFResult
    const groupRef = useRef<THREE.Group>(null)

    //  moves the geometry so its center of bounding box is at the local origin.
    nodes.model.geometry.center()

    const globalLenis = useScrollbar();

    useEffect(() => {
        if (globalLenis?.__lenis) {
            globalLenis.__lenis.on('scroll', ({ progress, velocity }) => {
                console.log({ progress });
                if (!groupRef.current) return;
                const scaleFactor = 0.05;
                const scale = (velocity * scaleFactor) + 1;

                groupRef.current.scale.set(scale, scale, scale)
                groupRef.current.rotation.y = progress * (Math.PI * 2)

            })
        }
    }, [globalLenis])

    return (
        <group {...props} dispose={null} ref={groupRef}>
            <mesh scale={100} castShadow receiveShadow geometry={nodes.model.geometry} material={materials.model}>
                <meshNormalMaterial />
            </mesh>
        </group>
    )
}

useGLTF.preload('/shades-compressed.glb')
